import * as THREE from "three";

const CONFIG = {
  DEBUG: false,
  BALL_SPEED: 15,
  PADDLE_VELOCITY_FACTOR: 20,
  BALL_INITIAL_POSITION: new THREE.Vector3(0, 10, 0),
  BALL_MAX_ANGLE: 45,
  BALL_INVINCIBLE_TIME: 1,
  BOSS_CLAW_HEALTH: 1,
  BOSS_BODY_HEALTH: 1,
};

export default CONFIG;
